name: flutter_launch
description: A Flutter plugin for iOS and Android to open whatsApp from a button.
author: Thyago Luciano <thyagoluciano@gmail.com>
version: 0.0.1
homepage: https://github.com/thyagoluciano/flutter_launch_whatsapp

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.flutterlaunch
    pluginClass: FlutterLaunchPlugin

environment:
  sdk: ">=1.19.0 <2.0.0"
